
Traceback (most recent call last):
  File "C:\Users\Dmitr\OneDrive\Документы\GitHub\verb-game-bot\vk_bot.py", line 66, in main
    echo(event, vk_api)
  File "C:\Users\Dmitr\OneDrive\Документы\GitHub\verb-game-bot\vk_bot.py", line 32, in echo
    raise Exception
Exception
